################################################################################
# This docker-compose file is only meant for e2e testing packages that
# require an S3 / dynamoDB connection:
# - test/routes.test.ts
# - packages/deploy-trigger
################################################################################

version: '3.6'

services:
  local-s3:
    image: minio/minio
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - s3-data:/data
    env_file:
      - ./test.env

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"

volumes:
  s3-data:
