# OpenAPI 3.0 schema for the API endpoints

openapi: 3.1.0

info:
  title: Terraform Next.js API
  version: 1.0.0

components:
  securitySchemes:
    sigv4:
      type: apiKey
      in: header
      name: Authorization
      'x-amazon-apigateway-authtype': 'awsSigv4'

  schemas:
    DeploymentStatus:
      type: string
      enum:
        - INITIALIZED
        - CREATE_COMPLETE
        - CREATE_FAILED

    DeploymentInitialized:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/DeploymentStatus'
        uploadUrl:
          type: string
      required:
        - id
        - status
        - uploadUrl

    Deployment:
      type: object
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/DeploymentStatus'
      required:
        - id
        - status

security:
  - sigv4: []

paths:
  /deployments/{deploymentId}:
    get:
      summary: Request a deployment by its Id.
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deployment'

  /deployments:
    post:
      summary: Initializes a new deployment and creates a upload link where the deployment package can be uploaded to.
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeploymentInitialized'
